### ISSUE TITLE
[zstring_view] Can't use as a template non-type parameter

### ISSUE THREAD

**Issue by vsytch** [openbmc/stdplus#5]
I need to pass strings as template non-type parameters and was hoping to use `zstring_view` for this, but unfortunately that doesn't work without some hacks.

With:
```
template <stdplus::zstring_view sensor_name>
struct Sensor{};
```
I get the following error - `error: 'stdplus::basic_zstring_view<char>' is not a valid type for a template non-type parameter because it is not structural`

Switching to:
```
template<size_t size>
using compile_zstring_view = stdplus::detail::compile_zstring_view<char, size>;

template <compile_zstring_view  sensor_name>
struct Sensor{};
```
Everything compiles OK.

Is there a proper way to do this without tapping into the implementation details of `zstring_view`?

**Comment by williamspatrick** [comment]
Can you use string_view in this way?

**Comment by wak-google** [comment]
std::string_view is not a structural type so no. I'm not really sure what the best way forward with this is because most types are inherently not structural and so they can't be used in this way. The `compile_zstring_view`  does what you want but it's not really a nice type to expose externally.

**Comment by vsytch** [comment]
Agreed, I'll stick to using a local implementation of `compile_zstring_view`.
